Split Printbox in three packages to make it easier to install exactly what we want
c-cube/printbox pull request #16
Opened 2021-05-27 16:29 UTC by mattiasdrp

dune is bad at looking at optional dependencies in opam and this looks like a "bad" feature in opam (at least it makes it hard to know what needs to be installed or not)

I refactored your repository to allow you to create three distinct packages thus allowing a finer control over what needs to be installed or not.

Notice that I tried to make it the smoothier I could so that anyone using one of the packages and previously already using them just has to put `open Printbox` (or `open Printbox_unicode` or `open Printbox_html`) and won't have nothing else to do.

This should be a better fix for #14

2021-05-27 23:21 UTC, c-cube commented
I agree that subpackages make sense, thank you. Could you revert the part where you move the `html` directory? There's no need to `printbox-` prefix the things :)

2021-05-27 23:54 UTC, c-cube requested changes
It's a good idea, but there's a lot of noise in this PR. I'd like, if possible, that the `src/html` directory remains (no useless prefixing), and no reindent/reformat of the rest :)

2021-05-28 07:48 UTC, mattiasdrp commented
I pushed a cleaner version ;-)

2021-05-28 15:17 UTC, merged

2021-05-28 15:17 UTC, c-cube commented
Perfect, thank you!

2021-05-28 15:18 UTC, c-cube commented
I'd take another PR for the tyxml part, if you have time :)

2021-05-28 15:25 UTC, c-cube commented
Yes exactly